### ISSUE TITLE
[Task] extonan web first alpha release checklist

### ISSUE THREAD

**Issue by ibnu-ja** [ibnu-ja/extonan#8]
Berikut merupakan list task sebelum rilis ke alpha.

- [ ] streaming untuk episode post
- [ ] MV post untuk shinrai
- [x] logo mobile
- [ ] tuning global promise based v-dialog component
- [x] draft system untuk posts
- [x] localization untuk posts
- [ ] halaman roadmap website
- [ ] halaman latest episode
- [ ] tuning/perbaikan component
  - [ ] latest anime slider pada home
  - [ ] anime banner pada index anime
- [ ] tuning/perbaikan halaman
  - [ ] index anime
  - [ ] show anime

### known bugs

- [ ] media: check remote upload image
